# Generated by Django 5.2.4 on 2025-08-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP_PORTAL', '0003_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='choice_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='choice_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='choice_3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
