# Generated by Django 5.2.4 on 2025-08-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP_PORTAL', '0005_studentprofile_chemistry_12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='tenth_board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='twelfth_board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='twelfth_stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
