# Generated by Django 5.2.4 on 2025-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP_PORTAL', '0006_alter_studentprofile_tenth_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='allocated_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
