# Generated by Django 5.2.4 on 2025-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP_PORTAL', '0007_studentprofile_allocated_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_staff_admin',
            field=models.BooleanField(default=False),
        ),
    ]
