# Generated by Django 5.2.4 on 2025-08-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP_PORTAL', '0008_userprofile_is_staff_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
